//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchoolModel", "FK_Course_Department", "Department", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContosoUniversity.Web.Department), "Course", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContosoUniversity.Web.Course))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchoolModel", "FK_OnlineCourse_Course", "Course", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContosoUniversity.Web.Course), "OnlineCourse", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ContosoUniversity.Web.OnlineCourse))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchoolModel", "FK_OnsiteCourse_Course", "Course", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContosoUniversity.Web.Course), "OnsiteCourse", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ContosoUniversity.Web.OnsiteCourse))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchoolModel", "FK_StudentGrade_Course", "Course", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContosoUniversity.Web.Course), "StudentGrade", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContosoUniversity.Web.StudentGrade))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchoolModel", "FK_OfficeAssignment_Person", "Person", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContosoUniversity.Web.Person), "OfficeAssignment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ContosoUniversity.Web.OfficeAssignment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchoolModel", "FK_StudentGrade_Student", "Person", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ContosoUniversity.Web.Person), "StudentGrade", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContosoUniversity.Web.StudentGrade))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SchoolModel", "CourseInstructor", "Course", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContosoUniversity.Web.Course), "Person", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ContosoUniversity.Web.Person))]

// Original file name:
// Generation date: 2/17/2011 10:43:47 AM
namespace ContosoUniversity.Web
{
    
    /// <summary>
    /// There are no comments for SchoolEntities in the schema.
    /// </summary>
    public partial class SchoolEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new SchoolEntities object using the connection string found in the 'SchoolEntities' section of the application configuration file.
        /// </summary>
        public SchoolEntities() : 
                base("name=SchoolEntities", "SchoolEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SchoolEntities object.
        /// </summary>
        public SchoolEntities(string connectionString) : 
                base(connectionString, "SchoolEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SchoolEntities object.
        /// </summary>
        public SchoolEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SchoolEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Course> Course
        {
            get
            {
                if ((this._Course == null))
                {
                    this._Course = base.CreateQuery<Course>("[Course]");
                }
                return this._Course;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Course> _Course;
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Department> Department
        {
            get
            {
                if ((this._Department == null))
                {
                    this._Department = base.CreateQuery<Department>("[Department]");
                }
                return this._Department;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Department> _Department;
        /// <summary>
        /// There are no comments for OfficeAssignment in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<OfficeAssignment> OfficeAssignment
        {
            get
            {
                if ((this._OfficeAssignment == null))
                {
                    this._OfficeAssignment = base.CreateQuery<OfficeAssignment>("[OfficeAssignment]");
                }
                return this._OfficeAssignment;
            }
        }
        private global::System.Data.Objects.ObjectQuery<OfficeAssignment> _OfficeAssignment;
        /// <summary>
        /// There are no comments for OnlineCourse in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<OnlineCourse> OnlineCourse
        {
            get
            {
                if ((this._OnlineCourse == null))
                {
                    this._OnlineCourse = base.CreateQuery<OnlineCourse>("[OnlineCourse]");
                }
                return this._OnlineCourse;
            }
        }
        private global::System.Data.Objects.ObjectQuery<OnlineCourse> _OnlineCourse;
        /// <summary>
        /// There are no comments for OnsiteCourse in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<OnsiteCourse> OnsiteCourse
        {
            get
            {
                if ((this._OnsiteCourse == null))
                {
                    this._OnsiteCourse = base.CreateQuery<OnsiteCourse>("[OnsiteCourse]");
                }
                return this._OnsiteCourse;
            }
        }
        private global::System.Data.Objects.ObjectQuery<OnsiteCourse> _OnsiteCourse;
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Person> Person
        {
            get
            {
                if ((this._Person == null))
                {
                    this._Person = base.CreateQuery<Person>("[Person]");
                }
                return this._Person;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Person> _Person;
        /// <summary>
        /// There are no comments for StudentGrade in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<StudentGrade> StudentGrade
        {
            get
            {
                if ((this._StudentGrade == null))
                {
                    this._StudentGrade = base.CreateQuery<StudentGrade>("[StudentGrade]");
                }
                return this._StudentGrade;
            }
        }
        private global::System.Data.Objects.ObjectQuery<StudentGrade> _StudentGrade;
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        public void AddToCourse(Course course)
        {
            base.AddObject("Course", course);
        }
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        public void AddToDepartment(Department department)
        {
            base.AddObject("Department", department);
        }
        /// <summary>
        /// There are no comments for OfficeAssignment in the schema.
        /// </summary>
        public void AddToOfficeAssignment(OfficeAssignment officeAssignment)
        {
            base.AddObject("OfficeAssignment", officeAssignment);
        }
        /// <summary>
        /// There are no comments for OnlineCourse in the schema.
        /// </summary>
        public void AddToOnlineCourse(OnlineCourse onlineCourse)
        {
            base.AddObject("OnlineCourse", onlineCourse);
        }
        /// <summary>
        /// There are no comments for OnsiteCourse in the schema.
        /// </summary>
        public void AddToOnsiteCourse(OnsiteCourse onsiteCourse)
        {
            base.AddObject("OnsiteCourse", onsiteCourse);
        }
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        public void AddToPerson(Person person)
        {
            base.AddObject("Person", person);
        }
        /// <summary>
        /// There are no comments for StudentGrade in the schema.
        /// </summary>
        public void AddToStudentGrade(StudentGrade studentGrade)
        {
            base.AddObject("StudentGrade", studentGrade);
        }
    }
    /// <summary>
    /// There are no comments for SchoolModel.Course in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CourseID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Course")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Course : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="courseID">Initial value of CourseID.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="credits">Initial value of Credits.</param>
        public static Course CreateCourse(int courseID, string title, int credits)
        {
            Course course = new Course();
            course.CourseID = courseID;
            course.Title = title;
            course.Credits = credits;
            return course;
        }
        /// <summary>
        /// There are no comments for Property CourseID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID
        {
            get
            {
                return this._CourseID;
            }
            set
            {
                this.OnCourseIDChanging(value);
                this.ReportPropertyChanging("CourseID");
                this._CourseID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CourseID");
                this.OnCourseIDChanged();
            }
        }
        private int _CourseID;
        partial void OnCourseIDChanging(int value);
        partial void OnCourseIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property Credits in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Credits
        {
            get
            {
                return this._Credits;
            }
            set
            {
                this.OnCreditsChanging(value);
                this.ReportPropertyChanging("Credits");
                this._Credits = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Credits");
                this.OnCreditsChanged();
            }
        }
        private int _Credits;
        partial void OnCreditsChanging(int value);
        partial void OnCreditsChanged();
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_Course_Department", "Department")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Department Department
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Department>("SchoolModel.FK_Course_Department", "Department").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Department>("SchoolModel.FK_Course_Department", "Department").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Department in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Department>("SchoolModel.FK_Course_Department", "Department");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Department>("SchoolModel.FK_Course_Department", "Department", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for OnlineCourse in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_OnlineCourse_Course", "OnlineCourse")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineCourse OnlineCourse
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OnlineCourse>("SchoolModel.FK_OnlineCourse_Course", "OnlineCourse").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OnlineCourse>("SchoolModel.FK_OnlineCourse_Course", "OnlineCourse").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for OnlineCourse in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<OnlineCourse> OnlineCourseReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OnlineCourse>("SchoolModel.FK_OnlineCourse_Course", "OnlineCourse");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<OnlineCourse>("SchoolModel.FK_OnlineCourse_Course", "OnlineCourse", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for OnsiteCourse in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_OnsiteCourse_Course", "OnsiteCourse")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public OnsiteCourse OnsiteCourse
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OnsiteCourse>("SchoolModel.FK_OnsiteCourse_Course", "OnsiteCourse").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OnsiteCourse>("SchoolModel.FK_OnsiteCourse_Course", "OnsiteCourse").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for OnsiteCourse in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<OnsiteCourse> OnsiteCourseReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OnsiteCourse>("SchoolModel.FK_OnsiteCourse_Course", "OnsiteCourse");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<OnsiteCourse>("SchoolModel.FK_OnsiteCourse_Course", "OnsiteCourse", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for StudentGrade in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_StudentGrade_Course", "StudentGrade")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<StudentGrade> StudentGrade
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<StudentGrade>("SchoolModel.FK_StudentGrade_Course", "StudentGrade");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<StudentGrade>("SchoolModel.FK_StudentGrade_Course", "StudentGrade", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "CourseInstructor", "Person")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Person> Person
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Person>("SchoolModel.CourseInstructor", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Person>("SchoolModel.CourseInstructor", "Person", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolModel.Department in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DepartmentID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Department")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Department : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Department object.
        /// </summary>
        /// <param name="departmentID">Initial value of DepartmentID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="budget">Initial value of Budget.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        public static Department CreateDepartment(int departmentID, string name, decimal budget, global::System.DateTime startDate)
        {
            Department department = new Department();
            department.DepartmentID = departmentID;
            department.Name = name;
            department.Budget = budget;
            department.StartDate = startDate;
            return department;
        }
        /// <summary>
        /// There are no comments for Property DepartmentID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID
        {
            get
            {
                return this._DepartmentID;
            }
            set
            {
                this.OnDepartmentIDChanging(value);
                this.ReportPropertyChanging("DepartmentID");
                this._DepartmentID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("DepartmentID");
                this.OnDepartmentIDChanged();
            }
        }
        private int _DepartmentID;
        partial void OnDepartmentIDChanging(int value);
        partial void OnDepartmentIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Budget in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Budget
        {
            get
            {
                return this._Budget;
            }
            set
            {
                this.OnBudgetChanging(value);
                this.ReportPropertyChanging("Budget");
                this._Budget = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Budget");
                this.OnBudgetChanged();
            }
        }
        private decimal _Budget;
        partial void OnBudgetChanging(decimal value);
        partial void OnBudgetChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this.ReportPropertyChanging("StartDate");
                this._StartDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StartDate");
                this.OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property Administrator in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> Administrator
        {
            get
            {
                return this._Administrator;
            }
            set
            {
                this.OnAdministratorChanging(value);
                this.ReportPropertyChanging("Administrator");
                this._Administrator = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Administrator");
                this.OnAdministratorChanged();
            }
        }
        private global::System.Nullable<int> _Administrator;
        partial void OnAdministratorChanging(global::System.Nullable<int> value);
        partial void OnAdministratorChanged();
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_Course_Department", "Course")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Course> Course
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Course>("SchoolModel.FK_Course_Department", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Course>("SchoolModel.FK_Course_Department", "Course", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolModel.OfficeAssignment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// InstructorID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="OfficeAssignment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class OfficeAssignment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new OfficeAssignment object.
        /// </summary>
        /// <param name="instructorID">Initial value of InstructorID.</param>
        /// <param name="location">Initial value of Location.</param>
        /// <param name="timestamp">Initial value of Timestamp.</param>
        public static OfficeAssignment CreateOfficeAssignment(int instructorID, string location, byte[] timestamp)
        {
            OfficeAssignment officeAssignment = new OfficeAssignment();
            officeAssignment.InstructorID = instructorID;
            officeAssignment.Location = location;
            officeAssignment.Timestamp = timestamp;
            return officeAssignment;
        }
        /// <summary>
        /// There are no comments for Property InstructorID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int InstructorID
        {
            get
            {
                return this._InstructorID;
            }
            set
            {
                this.OnInstructorIDChanging(value);
                this.ReportPropertyChanging("InstructorID");
                this._InstructorID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("InstructorID");
                this.OnInstructorIDChanged();
            }
        }
        private int _InstructorID;
        partial void OnInstructorIDChanging(int value);
        partial void OnInstructorIDChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this.ReportPropertyChanging("Location");
                this._Location = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Location");
                this.OnLocationChanged();
            }
        }
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Timestamp in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Timestamp
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Timestamp);
            }
            set
            {
                this.OnTimestampChanging(value);
                this.ReportPropertyChanging("Timestamp");
                this._Timestamp = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Timestamp");
                this.OnTimestampChanged();
            }
        }
        private byte[] _Timestamp;
        partial void OnTimestampChanging(byte[] value);
        partial void OnTimestampChanged();
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_OfficeAssignment_Person", "Person")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Person Person
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Person>("SchoolModel.FK_OfficeAssignment_Person", "Person").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Person>("SchoolModel.FK_OfficeAssignment_Person", "Person").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Person> PersonReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Person>("SchoolModel.FK_OfficeAssignment_Person", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Person>("SchoolModel.FK_OfficeAssignment_Person", "Person", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolModel.OnlineCourse in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CourseID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="OnlineCourse")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class OnlineCourse : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new OnlineCourse object.
        /// </summary>
        /// <param name="courseID">Initial value of CourseID.</param>
        /// <param name="uRL">Initial value of URL.</param>
        public static OnlineCourse CreateOnlineCourse(int courseID, string uRL)
        {
            OnlineCourse onlineCourse = new OnlineCourse();
            onlineCourse.CourseID = courseID;
            onlineCourse.URL = uRL;
            return onlineCourse;
        }
        /// <summary>
        /// There are no comments for Property CourseID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID
        {
            get
            {
                return this._CourseID;
            }
            set
            {
                this.OnCourseIDChanging(value);
                this.ReportPropertyChanging("CourseID");
                this._CourseID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CourseID");
                this.OnCourseIDChanged();
            }
        }
        private int _CourseID;
        partial void OnCourseIDChanging(int value);
        partial void OnCourseIDChanged();
        /// <summary>
        /// There are no comments for Property URL in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string URL
        {
            get
            {
                return this._URL;
            }
            set
            {
                this.OnURLChanging(value);
                this.ReportPropertyChanging("URL");
                this._URL = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("URL");
                this.OnURLChanged();
            }
        }
        private string _URL;
        partial void OnURLChanging(string value);
        partial void OnURLChanged();
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_OnlineCourse_Course", "Course")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Course Course
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("SchoolModel.FK_OnlineCourse_Course", "Course").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("SchoolModel.FK_OnlineCourse_Course", "Course").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Course> CourseReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("SchoolModel.FK_OnlineCourse_Course", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Course>("SchoolModel.FK_OnlineCourse_Course", "Course", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolModel.OnsiteCourse in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CourseID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="OnsiteCourse")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class OnsiteCourse : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new OnsiteCourse object.
        /// </summary>
        /// <param name="courseID">Initial value of CourseID.</param>
        /// <param name="location">Initial value of Location.</param>
        /// <param name="days">Initial value of Days.</param>
        /// <param name="time">Initial value of Time.</param>
        public static OnsiteCourse CreateOnsiteCourse(int courseID, string location, string days, global::System.DateTime time)
        {
            OnsiteCourse onsiteCourse = new OnsiteCourse();
            onsiteCourse.CourseID = courseID;
            onsiteCourse.Location = location;
            onsiteCourse.Days = days;
            onsiteCourse.Time = time;
            return onsiteCourse;
        }
        /// <summary>
        /// There are no comments for Property CourseID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseID
        {
            get
            {
                return this._CourseID;
            }
            set
            {
                this.OnCourseIDChanging(value);
                this.ReportPropertyChanging("CourseID");
                this._CourseID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CourseID");
                this.OnCourseIDChanged();
            }
        }
        private int _CourseID;
        partial void OnCourseIDChanging(int value);
        partial void OnCourseIDChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this.ReportPropertyChanging("Location");
                this._Location = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Location");
                this.OnLocationChanged();
            }
        }
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Days in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Days
        {
            get
            {
                return this._Days;
            }
            set
            {
                this.OnDaysChanging(value);
                this.ReportPropertyChanging("Days");
                this._Days = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Days");
                this.OnDaysChanged();
            }
        }
        private string _Days;
        partial void OnDaysChanging(string value);
        partial void OnDaysChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this.ReportPropertyChanging("Time");
                this._Time = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Time");
                this.OnTimeChanged();
            }
        }
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_OnsiteCourse_Course", "Course")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Course Course
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("SchoolModel.FK_OnsiteCourse_Course", "Course").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("SchoolModel.FK_OnsiteCourse_Course", "Course").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Course> CourseReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("SchoolModel.FK_OnsiteCourse_Course", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Course>("SchoolModel.FK_OnsiteCourse_Course", "Course", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolModel.Person in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PersonID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Person")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Person : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="personID">Initial value of PersonID.</param>
        /// <param name="lastName">Initial value of LastName.</param>
        /// <param name="firstName">Initial value of FirstName.</param>
        public static Person CreatePerson(int personID, string lastName, string firstName)
        {
            Person person = new Person();
            person.PersonID = personID;
            person.LastName = lastName;
            person.FirstName = firstName;
            return person;
        }
        /// <summary>
        /// There are no comments for Property PersonID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonID
        {
            get
            {
                return this._PersonID;
            }
            set
            {
                this.OnPersonIDChanging(value);
                this.ReportPropertyChanging("PersonID");
                this._PersonID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PersonID");
                this.OnPersonIDChanged();
            }
        }
        private int _PersonID;
        partial void OnPersonIDChanging(int value);
        partial void OnPersonIDChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this.ReportPropertyChanging("LastName");
                this._LastName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LastName");
                this.OnLastNameChanged();
            }
        }
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this.ReportPropertyChanging("FirstName");
                this._FirstName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FirstName");
                this.OnFirstNameChanged();
            }
        }
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property HireDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> HireDate
        {
            get
            {
                return this._HireDate;
            }
            set
            {
                this.OnHireDateChanging(value);
                this.ReportPropertyChanging("HireDate");
                this._HireDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HireDate");
                this.OnHireDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _HireDate;
        partial void OnHireDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnHireDateChanged();
        /// <summary>
        /// There are no comments for Property EnrollmentDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> EnrollmentDate
        {
            get
            {
                return this._EnrollmentDate;
            }
            set
            {
                this.OnEnrollmentDateChanging(value);
                this.ReportPropertyChanging("EnrollmentDate");
                this._EnrollmentDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EnrollmentDate");
                this.OnEnrollmentDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _EnrollmentDate;
        partial void OnEnrollmentDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnEnrollmentDateChanged();
        /// <summary>
        /// There are no comments for OfficeAssignment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_OfficeAssignment_Person", "OfficeAssignment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public OfficeAssignment OfficeAssignment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OfficeAssignment>("SchoolModel.FK_OfficeAssignment_Person", "OfficeAssignment").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OfficeAssignment>("SchoolModel.FK_OfficeAssignment_Person", "OfficeAssignment").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for OfficeAssignment in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<OfficeAssignment> OfficeAssignmentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<OfficeAssignment>("SchoolModel.FK_OfficeAssignment_Person", "OfficeAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<OfficeAssignment>("SchoolModel.FK_OfficeAssignment_Person", "OfficeAssignment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for StudentGrade in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_StudentGrade_Student", "StudentGrade")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<StudentGrade> StudentGrade
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<StudentGrade>("SchoolModel.FK_StudentGrade_Student", "StudentGrade");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<StudentGrade>("SchoolModel.FK_StudentGrade_Student", "StudentGrade", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "CourseInstructor", "Course")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Course> Course
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Course>("SchoolModel.CourseInstructor", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Course>("SchoolModel.CourseInstructor", "Course", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SchoolModel.StudentGrade in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EnrollmentID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="StudentGrade")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class StudentGrade : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new StudentGrade object.
        /// </summary>
        /// <param name="enrollmentID">Initial value of EnrollmentID.</param>
        public static StudentGrade CreateStudentGrade(int enrollmentID)
        {
            StudentGrade studentGrade = new StudentGrade();
            studentGrade.EnrollmentID = enrollmentID;
            return studentGrade;
        }
        /// <summary>
        /// There are no comments for Property EnrollmentID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int EnrollmentID
        {
            get
            {
                return this._EnrollmentID;
            }
            set
            {
                this.OnEnrollmentIDChanging(value);
                this.ReportPropertyChanging("EnrollmentID");
                this._EnrollmentID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EnrollmentID");
                this.OnEnrollmentIDChanged();
            }
        }
        private int _EnrollmentID;
        partial void OnEnrollmentIDChanging(int value);
        partial void OnEnrollmentIDChanged();
        /// <summary>
        /// There are no comments for Property Grade in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> Grade
        {
            get
            {
                return this._Grade;
            }
            set
            {
                this.OnGradeChanging(value);
                this.ReportPropertyChanging("Grade");
                this._Grade = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Grade");
                this.OnGradeChanged();
            }
        }
        private global::System.Nullable<decimal> _Grade;
        partial void OnGradeChanging(global::System.Nullable<decimal> value);
        partial void OnGradeChanged();
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_StudentGrade_Course", "Course")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Course Course
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("SchoolModel.FK_StudentGrade_Course", "Course").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("SchoolModel.FK_StudentGrade_Course", "Course").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Course> CourseReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Course>("SchoolModel.FK_StudentGrade_Course", "Course");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Course>("SchoolModel.FK_StudentGrade_Course", "Course", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_StudentGrade_Student", "Person")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Person Person
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Person>("SchoolModel.FK_StudentGrade_Student", "Person").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Person>("SchoolModel.FK_StudentGrade_Student", "Person").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Person in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Person> PersonReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Person>("SchoolModel.FK_StudentGrade_Student", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Person>("SchoolModel.FK_StudentGrade_Student", "Person", value);
                }
            }
        }
    }
}
